server:
  port: 8080
  servlet:
    context-path: /starter/api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trafficdb?serverTimezone=UTC
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    show-sql: false
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level.root: info

